### ISSUE TITLE
spi.transfer takes two arguments

### ISSUE THREAD

**Issue by deepsweb** [Freenove/Freenove_RFID_Starter_Kit_for_Raspberry_Pi#2]
Can you please tell me what below error means? I'm simply trying to run Read.py

 Traceback (most recent call last):
  File "RFID.py", line 12, in <module>
    mfrc = MFRC522.MFRC522()
  File "/home/pi/	MFRC522.py", line 115, in __init__
    self.MFRC522_Init()
  File "/home/pi/	MFRC522.py", line 412, in MFRC522_Init
    self.MFRC522_Reset();
  File "/home/pi/	MFRC522.py", line 118, in MFRC522_Reset
    self.Write_MFRC522(self.CommandReg, self.PCD_RESETPHASE)
  File "/home/pi/	MFRC522.py", line 121, in Write_MFRC522
    spi.transfer(((addr<<1)&0x7E,val))
TypeError: function takes exactly 2 arguments (1 given)

**Comment by SuhaylZhao** [comment]
Hi,

Please send me your wiring diagram and screenshots of the execution results. This will help us to identify your problems.

Thanks.

**Comment by deepsweb** [comment]
![image](https://user-images.githubusercontent.com/18683514/53309497-21731f80-3876-11e9-9312-428f1f62ee48.png)
![img_20190224_204544](https://user-images.githubusercontent.com/18683514/53309501-2b951e00-3876-11e9-82b8-eabea4e60157.jpg)
![img_20190224_204601](https://user-images.githubusercontent.com/18683514/53309502-2b951e00-3876-11e9-831d-351fa7bded16.jpg)

**Comment by SuhaylZhao** [comment]
Hi，

We found the solution to the problem. 

This is because the SPI-Py library has been updated recently, and the function has changed a lot, which is incompatible with the previous version.

Our solution is to provide previous versions of the SPI-Py library. We will then update the code to accommodate the latest version of the SPI-Py library.

You can download the previous version of the SPI-Py library here, https://github.com/Freenove/SPI-Py 

In addition, I find that the kit you use is not our product. But we still thank you for your questions. For our products, we provide free technical support. And our products are already welded, no need for customers to re-process. Welcome to our Amazon store，http://freenove.com/store.html .

Thanks again.

**Comment by deepsweb** [comment]
Thank you Suhayl!
It works now!
